name: Deploy OpenTofu VPC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.7.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Init tofu
        run: tofu init
        working-directory: ./tofu

      - name: Plan tofu
        run: tofu plan
        working-directory: ./tofu

      - name: Apply tofu
        run: tofu apply -auto-approve
        working-directory: ./tofu
        if: github.ref == 'refs/heads/main'
